### ISSUE TITLE
Build error: Redefinition of 'buf_size' as different kind of symbol

### ISSUE THREAD

**Issue by yohn89** [shadowsocks/Potatso#102]
```
Dev/Potatso/Library/ShadowPath/ShadowPath/shadowsocks-libev/src/udprelay.c:103:12: Redefinition of 'buf_size' as different kind of symbol
```

![](http://tyblog.qiniudn.com/16-9-2/77660475.jpg)

![](http://tyblog.qiniudn.com/16-9-2/82798563.jpg)

**Comment by yohn89** [comment]
fixed

**Comment by xiaobuu** [comment]
@yohn89 how did you fix the issue? I've met the same problem.

**Comment by yohn89** [comment]
@xiaobuu 
Look at this document : 
https://github.com/shadowsocks/Potatso/wiki/Setup-Guide

**Comment by xiaobuu** [comment]
@yohn89 Would you mind providing more details? I've followed guide already, and I can't fix it by looking at the document.

**Comment by whlsxl** [comment]
I have the same issue,
the reason is I run on simulator, but simulator have a function named `buf_size `, so there is redefinition,
run on device will fix this problem

**Comment by laoyur** [comment]
same issue here 
Xcode 7.3.1
iOS Emulator 9.3

**Comment by LuffyZWQ** [comment]
@whlsxl  How did you run on device ? I run failed because of the bundle id . Would you mind providing more details?

**Comment by LuffyZWQ** [comment]
@xiaobuu  Have you fixed the issue ? I met the same problem ,Would you mind providing more details?

**Comment by laoyur** [comment]
@LuffyZWQ quite easy, just rename `buf_size` and refs to `buff_size` or something else
