### ISSUE TITLE
想请问一下作者今后关于开源&收费的策略~

### ISSUE THREAD

**Issue by 0x5e** [shadowsocks/Potatso#32]
首先感谢作者的开源~然后想问一下今后的版本更新是否用的就是这个仓库，是否接受Pull requests，接受的话上架的app还收费吗，感觉这两者有些矛盾呢。。。

**Comment by icodesign** [comment]
> 想问一下今后的版本更新是否用的就是这个仓库

是的

> 是否接受Pull requests

和任何的开源项目一样，所以接受

> 接受的话上架的app还收费吗，感觉这两者有些矛盾呢

收费，开源和收费并不矛盾

**Comment by Naville** [comment]
那么如果有人赞助99$的话，App Store版是不是可以变成免费＋广告的模式

**Comment by icodesign** [comment]
收费是我能够持续维护的动力，希望大家支持
