### ISSUE TITLE
爱奇艺视频播放的BUG！

### ISSUE THREAD

**Issue by HenrieWu** [shadowsocks/Potatso#33]
转surge的规则。
注：排除surge规则开头部分bypass-tun、skip-proxy之类的，还有结尾的FINAL,Proxy不同，其他的规则完全相同。

potatso套用此规则+全局模式。
爱奇艺部分视频无法播放，提示：“你所在的地区无法观看该视频....。”猜测应该部分视频链接走代理了。

用surge找到potatso提示无法观看的视频，没这个问题。

**Comment by icodesign** [comment]
规则附一下

**Comment by HenrieWu** [comment]
今天更新了TF版1.39（94）发现：
1、potatso开启全局，爱奇艺视频部分无法播放，提示区域限制。但是关闭全局开关，无法播放的视频竟然能播放了。

2、使用默认dns，无法屏蔽掉视频开头广告。自定义dns208.67.222.222,119.29.29.29，广告没有了。

规则：https://gist.github.com/HenrieWu/6eb1fac2ab814a965bb3a40d3b779545
