### ISSUE TITLE
PotatsoMoldels下"Realm/Rlmarray.h" Not found

### ISSUE THREAD

**Issue by kokomoji** [shadowsocks/Potatso#36]
Hi,
  我用CocoaPods更新过，用Carthage update也更新了，不知道还有什么没有做的。Xcode Build的时候，还是在PotatsoMoldels下提示"Realm/Rlmarray.h" Not found  请指教一下该如何解决，谢谢~

**Comment by ChaosTong** [comment]
哈哈，这个我会，按住Option 点击Xcode 工具栏的 Product 选择 Clean Builder Folder, 如果弹出权限问题就，先不按住Option Clean一下。
source from:https://github.com/realm/realm-cocoa/issues/3551

**Comment by kokomoji** [comment]
@ChaosTong 兄弟我爱你~~ 么么哒
我搞了两天，又是从这get,从那get. build一个工程都把我搞晕了。

**Comment by ChaosTong** [comment]
我每天来这看看有没有人提这个问题，终于有人提了。哈哈

**Comment by icodesign** [comment]
@ChaosTong 
虽然我的 License 不能阻止你上架 App Store，但我建议您把 App Store 上的 App 好好改改再提交上去，而不是原样提交，连 App 描述都照抄，技术人员是要有节操的。

**Comment by Naville** [comment]
走国技术人员的节操看BAT就知道了
ROFL

**Comment by ChaosTong** [comment]
@icodesign my fault, 这就下架，不多狡辩了.

**Comment by MofeLee** [comment]
刚在AppStore买过的怎么办？

**Comment by icodesign** [comment]
@MofeLee 我们在说的是 @ChaosTong  上架的一个类似的 App， 如果你买的是 Potatso，那么跟这个无关，如果你买的不是 Potatso，跟我无关

**Comment by MofeLee** [comment]
嗯，原来如此，我买的是Potatso~
