### ISSUE TITLE
BUG！开启全局开关，路由器192.168.1.1无法打开。

### ISSUE THREAD

**Issue by HenrieWu** [shadowsocks/Potatso#39]
如题！
Safari提示：Safari打不开该网页，因为已丢失网络链接。
不开启全局开关是可以访问的。

**Comment by cccRaim** [comment]
你都全局了。。。当然访问不了，这是使用问题

**Comment by HenrieWu** [comment]
Potatso的全局开关-----》相当于--------》surge规则的final,proy

surge是通过bypass-tun之类的跳过内网段的，Potatso怎么处理的不清楚。

**Comment by cccRaim** [comment]
你没懂代理的使用方法，代理并不是用来翻得工具，一开始是为了创建工作环境使用的，使用代理可以远程连入内网，如果跳过内网段，你就不能连到工作区的内网了

**Comment by HenrieWu** [comment]
那你可否解释下surge全局情况下是怎么实现的？

**Comment by cccRaim** [comment]
你写了bypass-tun当然就忽略不走代理了

**Comment by HenrieWu** [comment]
那不就结了！有可以实现的方法不是？
难道potatso这叫全局，surge实现的全局不叫全局？

而且作者也说过：Potatso的全局开关-----》相当于--------》surge规则的final,proy

这是使用问题？

**Comment by icodesign** [comment]
@HenrieWu 你加一条 rule：IP-CIDR, 192.168.0.0/16, DIRECT，然后试试
