### ISSUE TITLE
希望能加入ShadowsocksR的支持

### ISSUE THREAD

**Issue by quericy** [shadowsocks/Potatso#4]
如题，ShadowsocksR的混淆功能在很多地方还是非常有用处的

**Comment by peiweichen** [comment]
请问 现在的 shadowsocks支持 无间断的全局配置吗？ 也就是说在其他app的流量也经过 ss ?

**Comment by icodesign** [comment]
@peiweichen 是的，除 UDP 以外

**Comment by icodesign** [comment]
https://github.com/breakwa11/shadowsocks-libev
