### ISSUE TITLE
Pull了最新的代码 执行git submodule update --init时报错

### ISSUE THREAD

**Issue by xiaobuu** [shadowsocks/Potatso#46]
fatal: reference is not a tree: 09bd8bcbf9b708c085f9f2b334fd14a1575ab286
Unable to checkout '09bd8bcbf9b708c085f9f2b334fd14a1575ab286' in submodule path 'Library/ShadowPath/ShadowPath/shadowsocks-libev'

**Comment by fengzhichu** [comment]
遇到同样的问题

**Comment by kongfanwu** [comment]
遇到同样的问题

**Comment by icodesign** [comment]
重来一次呢？

**Comment by mashun** [comment]
shadowsocks-libev直接下载到potatso目录下吗？还是添加到ShadowPath目录下

**Comment by xiaobuu** [comment]
确实没有额 https://github.com/icodesign/shadowsocks-libev/tree/09bd8bcbf9b708c085f9f2b334fd14a1575ab286

**Comment by luzhenzhao** [comment]
直接下来一份下来也不行，shadowsocks-libev是源码，ShadowPath里面是编译过的，有config.h，源码没有config.h，这个应该怎么破呢。。

**Comment by mashun** [comment]
Fetched in submodule path 'Library/ShadowPath/ShadowPath/shadowsocks-libev', but it did not contain 09bd8bcbf9b708c085f9f2b334fd14a1575ab286. Direct fetching of that commit failed.
我这边一直报这个错

**Comment by CodeEagle** [comment]
@icodesign 自己`fork`了一份[`shadowsocks-libev`](https://github.com/icodesign/shadowsocks-libev)并修改为`iOS`可用,但是删除了`commit: 09bd8bc `,当前[`shadowsocks-libev`](https://github.com/icodesign/shadowsocks-libev)的`commit`是`c0f0598`,所以在@icodesign更新前，这个repo仍旧不可用

**Comment by CoderJin** [comment]
![a2facca1-a647-48d7-b99d-92aa32e67c1e](https://cloud.githubusercontent.com/assets/18577384/16962063/ab679428-4e22-11e6-8bd1-889e906b32d1.png)
![bf03dcd1-9be7-4ccb-8b5c-0cfe843199eb](https://cloud.githubusercontent.com/assets/18577384/16962076/bd2b5ffa-4e22-11e6-98ca-e2845d42666d.png)这个文件夹就是空的 后面的连接也是找不到..

**Comment by icodesign** [comment]
已更新 shadowsocks-libev 这个库

**Comment by CodeEagle** [comment]
@icodesign hey man,
![image](https://cloud.githubusercontent.com/assets/2311352/16976932/6e1ae2d8-4e85-11e6-82dd-185d79c7a253.png)
项目还是缺少这个？是要自己编译么？

**Comment by CoderJin** [comment]
是不是直接改这个文件,但是改了其他地方也报错..
![image](https://cloud.githubusercontent.com/assets/18577384/16977588/8b77a182-4e89-11e6-8ee1-5f79fea5e74c.png)

**Comment by jackyzh** [comment]
@CoderJin @CodeEagle run 一下 configure 会自动生成 config.h 文件，但是不知道是不是正确的姿势

**Comment by CodeEagle** [comment]
@jackyzh thanks

**Comment by mashun** [comment]
出现这个configure: error: OpenSSL header files not found.错

**Comment by jackyzh** [comment]
@CodeEagle @mashun 

    brew install openssl
    brew link openssl --force`

google 一下就有了 =.=

**Comment by CodeEagle** [comment]
可能是升级了系统，需要`xcode-select --install`

**Comment by mashun** [comment]
又出现这个了
![image](https://cloud.githubusercontent.com/assets/8759050/16979110/f4f63148-4e91-11e6-80bd-6c83d3df8a86.png)

**Comment by azureplus** [comment]
./configure --with-openssl="{userpath}/ShadowPath/ShadowPath/libopenssl"  这样就行

**Comment by azureplus** [comment]
是在终端下，不是直接点开

**Comment by azureplus** [comment]
我昨天已经解决了，今天作者已经提交了一个版本

**Comment by mashun** [comment]
执行完，
![image](https://cloud.githubusercontent.com/assets/8759050/16979298/dfbeb506-4e92-11e6-9c35-9c96b0ab665b.png)，还是
![image](https://cloud.githubusercontent.com/assets/8759050/16979311/ef5fc676-4e92-11e6-86b5-1c4a9a6007fe.png)

**Comment by mashun** [comment]
下的今天的新版本

**Comment by azureplus** [comment]
configure 后你还要make

**Comment by mashun** [comment]
什么意思？make什么？

**Comment by azureplus** [comment]
233333333，哎，执行完 configure后，继续输入 make命令，再回车。。。

**Comment by icodesign** [comment]
@azureplus ./configure 就可以了，会生成 config.h，不需要 make

**Comment by azureplus** [comment]
嗯，这个过程，xcode去做了

**Comment by CoderJin** [comment]
![image](https://cloud.githubusercontent.com/assets/18577384/16980672/c2189c04-4e99-11e6-9160-9acd29010423.png)
 ni'men你们有报这个错误吗?

**Comment by CodeEagle** [comment]
具体的流程，
1.下载下来，`pod install`, 'carthage update'
2.下载 shadowsocks-libev, 确认‘xcode-select --install’ 之后，./configure --with-openssl="{userpath}/ShadowPath/ShadowPath/libopenssl" 这样就行

**Comment by azureplus** [comment]
可以开个QQ群嘛

**Comment by icodesign** [comment]
@azureplus  不可以

**Comment by azureplus** [comment]
The entitlements specified in your application’s Code Signing Entitlements file do not match those specified in your provisioning profile. (0xE8008016).

**Comment by CodeEagle** [comment]
真机跑不了的，改了id的话，要申请 network extension entitlements 的

**Comment by azureplus** [comment]
需要申请 network extension entitlements

**Comment by GHYuan928** [comment]
![Uploading 923F4C89-AC39-4144-B417-3BF80FC4D8C5.png…]()
我把 shadow socks-libev 下载添加进去了，出现1 #include <libcork/core.h>没有找到，2 config.h 还是红色的，如何解决，help---

**Comment by GHYuan928** [comment]
[Uploading 923F4C89-AC39-4144-B417-3BF80FC4D8C5.png…]()
我把 shadow socks-libev 下载添加进去了，出现1 #include <libcork/core.h>没有找到，2 config.h 还是红色的，如何解决，help---

**Comment by XyxXiang** [comment]
@CodeEagle  大神，你用的Xcode版本的多少的？   
我按照你写的流程，先pod然后carthage，再加入shadow-libv,但是最后还是有错误，错误主要是在ProxyRow.swift里面的，很多语法错误..    你调试的时候也遇到这些错误了吗？

**Comment by CodeEagle** [comment]
我之前弄的时候是2.3的，现在3.语法，这个项目还没升级的话，应该会报错吧，这个是语法的错
