### ISSUE TITLE
编译遇到这种错误，应该怎么处理？

### ISSUE THREAD

**Issue by welkinwalker** [shadowsocks/Potatso#49]
![qq20160718-0 2x](https://cloud.githubusercontent.com/assets/3654374/16911855/78a1f200-4d13-11e6-93e0-d6bdbfd40075.png)

**Comment by mashun** [comment]
我也遇到了

**Comment by azureplus** [comment]
缺这个 tls1.2_ticket.c

**Comment by xiaobuu** [comment]
#46 估计是这个submodule的问题

**Comment by welkinwalker** [comment]
@xiaobuu 
fatal: reference is not a tree: 09bd8bcbf9b708c085f9f2b334fd14a1575ab286
Unable to checkout '09bd8bcbf9b708c085f9f2b334fd14a1575ab286' in submodule path 'Library/ShadowPath/ShadowPath/shadowsocks-libev'
这个错误我也报，然后我自己clone了一个shadowsocks-libev到了指定目录，然后编译 就报我截图的这个错误

**Comment by mashun** [comment]
我把tls1.2_ticket.c添加进去，还是报这个错

**Comment by azureplus** [comment]
估计是跟环境有关系

**Comment by welkinwalker** [comment]
定义obfs的obfs.h加入了build phase里的Headers里面了，但是却找不到响应的定义。

**Comment by Kingson** [comment]
same issue!

**Comment by icodesign** [comment]
感谢各位，已更新
