### ISSUE TITLE
Fatal error: can't load actions file 'potatso.action'

### ISSUE THREAD

**Issue by undoubted** [shadowsocks/Potatso#51]
ipad4 wifi 1.4.1 版连接时报错
`Fatal error: can't load actions file 'potatso.action': No such file or directory. Note that beginning with Privoxy 3.0.7, actions files have to be specified with their complete file names.`

**Comment by thomasbarwanitz** [comment]
Am Sonntag, 24. Juli 2016 schrieb undoubted :

**Comment by icodesign** [comment]
Will be fixed in next version.

**Comment by undoubted** [comment]
fixed in 1.4.4. thanks!
