### ISSUE TITLE
git submodule update --init | error on Library/ShadowPath/ShadowPath/libmaxminddb

### ISSUE THREAD

**Issue by XUJiahua** [shadowsocks/Potatso#53]
please help, 

```
⇒  git submodule update --init

fatal: reference is not a tree: 569b762feb605001bd3dc4258074eba8b8b4d993
Unable to checkout '569b762feb605001bd3dc4258074eba8b8b4d993' in submodule path 'Library/ShadowPath/ShadowPath/libmaxminddb'
```

**Comment by daheli** [comment]
me too ~

**Comment by xcoderliu** [comment]
just download directly

**Comment by raykin** [comment]
@xcoderliu what command do you used for downloading?

**Comment by GHYuan928** [comment]
git submodule update --init


Cloning into 'Library/ShadowPath/ShadowPath/libmaxminddb'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:maxmind/libmaxminddb.git' into submodule path 'Library/ShadowPath/ShadowPath/libmaxminddb' failed

Help~

**Comment by icodesign** [comment]
I've updated the submodules, could you have a try now?

**Comment by XUJiahua** [comment]
similar error:

⇒  git submodule update --init
fatal: reference is not a tree: 7dff85abaf934e0868dd5ac9d38d807c01bd7888
Unable to checkout '7dff85abaf934e0868dd5ac9d38d807c01bd7888' in submodule path 'Library/ShadowPath/ShadowPath/libmaxminddb'
