### ISSUE TITLE
About Setup-Guide

### ISSUE THREAD

**Issue by daheli** [shadowsocks/Potatso#58]
After I clone, I got some mistakes in the following commands.

> git submodule update --init

```
Cloning into 'Library/ShadowPath/ShadowPath/libmaxminddb'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:maxmind/libmaxminddb.git' into submodule path 'Library/ShadowPath/ShadowPath/libmaxminddb' failed
```

**Comment by daheli** [comment]
> cat .gitmodules

```
[submodule "Library/ShadowPath/ShadowPath/shadowsocks-libev"]
	path = Library/ShadowPath/ShadowPath/shadowsocks-libev
	url = git@github.com:icodesign/shadowsocks-libev.git
[submodule "Library/ShadowPath/ShadowPath/libmaxminddb"]
	path = Library/ShadowPath/ShadowPath/libmaxminddb
	url = git@github.com:maxmind/libmaxminddb.git
```

**Comment by daheli** [comment]
**You could change the url configuration to https url and everything works,** but this is not the perfect solution, because the address git@github.com is perfectly valid, but probably there is some problem with your RSA keys stored in Github (or you never configured RSA Keys for your account). In my situation, my RSA Keys had some problem and I needed to recreate another one. If you do not know what a RSA key is and how to create a RSA Key to connect to github I strongly suggest you reading the guide: [Generating SSH Keys.](http://stackoverflow.com/questions/25957125/git-submodule-permission-denied)

**Comment by GHYuan928** [comment]
pls use Mandarin

**Comment by danwey** [comment]
Cloning into 'Library/ShadowPath/ShadowPath/libmaxminddb'...
remote: Counting objects: 4884, done.
remote: Total 4884 (delta 0), reused 0 (delta 0), pack-reused 4884
Receiving objects: 100% (4884/4884), 1.12 MiB | 68.00 KiB/s, done.
Resolving deltas: 100% (2642/2642), done.
Checking connectivity... done.
fatal: reference is not a tree: 569b762feb605001bd3dc4258074eba8b8b4d993

The problem, how do you get?

**Comment by tianfire** [comment]
I checkout maxminddb from github and copy it to /shadowpath

**Comment by daheli** [comment]
@tianfire 
This is the only way :(

**Comment by icodesign** [comment]
@daheli You'd better setup your computer to be compatible with GitHub so that to avoid some problems.

**Comment by icodesign** [comment]
I've updated the submodules, could you have a try now?

**Comment by likenow** [comment]
After I clone, I also got some mistakes in the following commands.

git submodule update --init

Cloning into 'Library/ShadowPath/ShadowPath/libmaxminddb'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:icodesign/libmaxminddb.git' into submodule path 'Library/ShadowPath/ShadowPath/libmaxminddb' failed

$ cat .gitmodules
[submodule "Library/ShadowPath/ShadowPath/shadowsocks-libev"]
	path = Library/ShadowPath/ShadowPath/shadowsocks-libev
	url = git@github.com:icodesign/shadowsocks-libev.git
[submodule "Library/ShadowPath/ShadowPath/libmaxminddb"]
	path = Library/ShadowPath/ShadowPath/libmaxminddb
	url = git@github.com:icodesign/libmaxminddb.git

**Comment by icodesign** [comment]
@likenow I've said in another issue:
> No offence. But unfortunately, I don't think you have a basic understanding of how Git and GitHub works. You should consult Google or GitHub user manual. And I'm sorry that this project may not suitable for learning on a whim for now.
