### ISSUE TITLE
ShadowPath "libcork/core.h" file not found

### ISSUE THREAD

**Issue by GHYuan928** [shadowsocks/Potatso#60]
在ShadowPath 中 inspection.c 看到 导入头文件 `#include<libcork/core.h>` 出现 "libcork/core.h" file not found, 不知道什么原因导致 找不到文件。help. 环境搞了几天还是出现问题

**Comment by GHYuan928** [comment]
还发现 在 Potato 中有个 红色的 confidential.h ，这个文件也没有。有没大神帮忙看下，什么问题

**Comment by wenerme** [comment]
@GHYuan928 请问你是怎么解决的呢

**Comment by GHYuan928** [comment]
@wenerme  按照  #2   来做，基本 没问题

**Comment by Steven-Luo** [comment]
和你遇到了同样的问题，也是折腾了好久，最后发现是头文件的搜索路径有问题，不知道为什么找不到那个目录，把截图中的Header Search Paths和Library Search Paths中加入Potatso/Library/ShadowPath/ShadowPath/shadowsocks-libev/libcork/include的绝对路径，重新编译即可

![2016-10-08 11 14 31](https://cloud.githubusercontent.com/assets/3992893/19214036/04c66b74-8dad-11e6-9781-a3a92326448e.png)

**Comment by thomasbarwanitz** [comment]
Am Mittwoch, 27. Juli 2016 schrieb GHYuan928 :

**Comment by aishuidedabai** [comment]
能否发一份借鉴一下，被逼疯了，1404019775@qq.com
