### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by CoderJin** [shadowsocks/Potatso#80]
![b43afe8af2302f3171309c9839365ae4](https://cloud.githubusercontent.com/assets/18577384/17643669/79d8da68-61a3-11e6-8a79-1d664d0c08f0.jpg)
Shadowrocket 在这边直接点击链接会跳转到自己的 app  ,进行 connect, 而 potatso 点击 connect 的时候,不跳转,总是链接不上 ,这个算 bug 吧...
ui 方面感觉你比它那个强,但是对于小白的来说 ,总感觉你界面不知道怎么配置

**Comment by Douglas1997** [comment]
没有吧?我在IOS9上面连接没问题。
我觉得这个设计很好。你应该是配置或者其他的问题。

**Comment by CoderJin** [comment]
你有同时安装两个客户端测试吗?

**Comment by jefby** [comment]
iOS 9.3.4 Potatso 1.4.6 Build 122没问题
